version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_uaifood
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=uaifood
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3306:3306'
    networks:
      - uaifood_bridge_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

# For local tests to debug purposes comment the service bellow
  uaifood-app:
    image: 'uaifood:2.0.0'
    container_name: uaifood_app
    environment:
      - SCOPE=production
      - MYSQL_CONN_URL=jdbc:mysql://mysql:3306/uaifood
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '8080:8080'
    networks:
      - uaifood_bridge_network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  uaifood_bridge_network:
    driver: bridge